FROM almalinux:8
RUN yum update -y
RUN yum install stress-ng -y
CMD ["stress-ng", "--help"]



#it will control wihtout eating up all resources if anything wrong in code or in error occured acts like rations