apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hr
    trainer: siva
  annotations:
    org.docker.loa.nginx.show.off: siva
spec:
  containers:
  - image: nginx
    name: nginx
    