apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - image: nginx
    name: nginx
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: course
    - name: trainer
      value: pritam