apiVersion: v1
kind: Pod
metadata: 
  name:resource
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"   # 1cpu = 1000milli
      limits:
        memory: "128Mi"
        cpu: "500m"
      