---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx1
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    server: nginx1
  ports:
    - protocol: TCP
      port: 80
      targetport: 80
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376